#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const configPath = path.join(rootDir, 'capacitor.config.json');
const activeEnvPath = path.join(rootDir, '.active-env');
const iosXconfigDir = path.join(rootDir, 'ios');
const androidAppDir = path.join(rootDir, 'android', 'app');
const androidAssetsConfigPath = path.join(androidAppDir, 'src', 'main', 'assets', 'capacitor.config.json');
const androidStringsPath = path.join(androidAppDir, 'src', 'main', 'res', 'values', 'strings.xml');
const androidEnvGradlePath = path.join(androidAppDir, 'environment.gradle');
const androidBuildGradlePath = path.join(androidAppDir, 'build.gradle');

const envConfigs = {
  local: {
    name: 'Local',
    url: 'https://pants-unshaken-stony.ngrok-free.dev/login',
    applicationIdSuffix: '.local',
    versionNameSuffix: '-local',
    bundleIdSuffix: '.local',
    displayName: 'Setli LOCAL',
    xconfigFile: 'env-local.xcconfig'
  },
  dev: {
    name: 'Development',
    url: 'https://dev.setli.com.au/login',
    applicationIdSuffix: '.dev',
    versionNameSuffix: '-dev',
    bundleIdSuffix: '.dev',
    displayName: 'Setli DEV',
    xconfigFile: 'env-dev.xcconfig'
  },
  prod: {
    name: 'Production',
    url: 'https://setli.com.au/login',
    applicationIdSuffix: '',
    versionNameSuffix: '',
    bundleIdSuffix: '',
    displayName: 'Setli',
    xconfigFile: 'env-prod.xcconfig'
  },
  production: {
    name: 'Production',
    url: 'https://setli.com.au/login',
    applicationIdSuffix: '',
    versionNameSuffix: '',
    bundleIdSuffix: '',
    displayName: 'Setli',
    xconfigFile: 'env-prod.xcconfig'
  }
};

const args = process.argv.slice(2);
const requestedEnv = (args[0] || 'prod').toLowerCase();
const shouldSync = args.includes('--sync') || args.includes('-s');

const targetEnv = envConfigs[requestedEnv];

if (!targetEnv) {
  console.error(`❌ Unknown environment "${requestedEnv}". Available: local, dev, prod`);
  process.exit(1);
}

if (!fs.existsSync(configPath)) {
  console.error(`❌ capacitor.config.json not found at "${configPath}".`);
  process.exit(1);
}

try {
  const normalizedEnv = requestedEnv === 'production' ? 'prod' : requestedEnv;

  // 1. Update root capacitor.config.json server.url
  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  if (!config.server) config.server = {};
  config.server.url = targetEnv.url;
  const updatedConfigJson = JSON.stringify(config, null, 2) + '\n';
  fs.writeFileSync(configPath, updatedConfigJson, 'utf8');

  // 2. Also directly update android assets capacitor.config.json to ensure immediate sync
  if (fs.existsSync(path.dirname(androidAssetsConfigPath))) {
    fs.writeFileSync(androidAssetsConfigPath, updatedConfigJson, 'utf8');
  }

  // 3. Write active environment marker
  fs.writeFileSync(activeEnvPath, normalizedEnv, 'utf8');

  // 4. Update Android environment.gradle
  const envGradleContent = [
    `// Auto-generated by scripts/set-env.js — do not edit manually`,
    `// Active Environment: ${targetEnv.name.toUpperCase()}`,
    `ext {`,
    `    activeApplicationIdSuffix = "${targetEnv.applicationIdSuffix}"`,
    `    activeVersionNameSuffix = "${targetEnv.versionNameSuffix}"`,
    `    activeAppName = "${targetEnv.displayName}"`,
    `}`,
    ``
  ].join('\n');
  fs.writeFileSync(androidEnvGradlePath, envGradleContent, 'utf8');

  // 5. Touch android/app/build.gradle timestamp so Android Studio detects the change
  if (fs.existsSync(androidBuildGradlePath)) {
    const now = new Date();
    fs.utimesSync(androidBuildGradlePath, now, now);
  }

  // 6. Update Android strings.xml app_name and title
  if (fs.existsSync(androidStringsPath)) {
    const stringsContent = [
      `<?xml version='1.0' encoding='utf-8'?>`,
      `<resources>`,
      `    <string name="app_name">${targetEnv.displayName}</string>`,
      `    <string name="title_activity_main">${targetEnv.displayName}</string>`,
      `    <string name="package_name">com.setli.app${targetEnv.applicationIdSuffix}</string>`,
      `    <string name="custom_url_scheme">com.setli.app${targetEnv.applicationIdSuffix}</string>`,
      `</resources>`,
      ``
    ].join('\n');
    fs.writeFileSync(androidStringsPath, stringsContent, 'utf8');
  }

  // 7. Update iOS xcconfig files
  const envXcconfigs = {
    'env-local.xcconfig': {
      SETLI_BUNDLE_ID_SUFFIX: '.local',
      SETLI_DISPLAY_NAME: 'Setli LOCAL',
      SETLI_ENV: 'local'
    },
    'env-dev.xcconfig': {
      SETLI_BUNDLE_ID_SUFFIX: '.dev',
      SETLI_DISPLAY_NAME: 'Setli DEV',
      SETLI_ENV: 'dev'
    },
    'env-prod.xcconfig': {
      SETLI_BUNDLE_ID_SUFFIX: '',
      SETLI_DISPLAY_NAME: 'Setli',
      SETLI_ENV: 'prod'
    }
  };

  for (const [filename, vars] of Object.entries(envXcconfigs)) {
    const xcLines = [
      `// Auto-generated by scripts/set-env.js — do not edit manually`,
      `// Environment: ${vars.SETLI_ENV}`,
      ``,
      `SETLI_BUNDLE_ID_SUFFIX = ${vars.SETLI_BUNDLE_ID_SUFFIX}`,
      `SETLI_DISPLAY_NAME = ${vars.SETLI_DISPLAY_NAME}`,
      `SETLI_ENV = ${vars.SETLI_ENV}`,
      ``
    ].join('\n');
    fs.writeFileSync(path.join(iosXconfigDir, filename), xcLines, 'utf8');
  }

  // 8. Update debug.xcconfig
  const debugXcconfig = [
    `// Capacitor debug config — do not edit manually`,
    `CAPACITOR_DEBUG = true`,
    ``,
    `// Active environment overrides`,
    `#include "${targetEnv.xconfigFile}"`,
    ``
  ].join('\n');
  fs.writeFileSync(path.join(iosXconfigDir, 'debug.xcconfig'), debugXcconfig, 'utf8');

  // 9. Update release.xcconfig
  const releaseXcconfig = [
    `// Capacitor release config — do not edit manually`,
    ``,
    `// Active environment overrides`,
    `#include "${targetEnv.xconfigFile}"`,
    ``
  ].join('\n');
  fs.writeFileSync(path.join(iosXconfigDir, 'release.xcconfig'), releaseXcconfig, 'utf8');

  console.log(`\n======================================================`);
  console.log(`🚀 Switched Setli App Environment to: [ ${targetEnv.name.toUpperCase()} ]`);
  console.log(`🌐 Server URL:        ${targetEnv.url}`);
  console.log(`🤖 Android App ID:    com.setli.app${targetEnv.applicationIdSuffix}`);
  console.log(`   Android App Name:  ${targetEnv.displayName}`);
  console.log(`   Version Suffix:    ${targetEnv.versionNameSuffix || '(none — production)'}`);
  console.log(`📱 iOS Bundle ID:     com.setli.app${targetEnv.bundleIdSuffix}`);
  console.log(`   iOS Display Name:  ${targetEnv.displayName}`);
  console.log(`======================================================\n`);

  if (shouldSync) {
    console.log(`🔄 Syncing with iOS and Android native projects via Capacitor...\n`);
    execSync('npx cap sync', { stdio: 'inherit', cwd: rootDir });
    console.log(`\n✅ Successfully synced ${targetEnv.name} environment to iOS and Android!`);
  } else {
    console.log(`ℹ️  Run "npm run sync" to apply changes to native projects.`);
  }
} catch (error) {
  console.error(`❌ Failed to update environment:`, error.message);
  process.exit(1);
}
